name: qgis_plugin

services:
  qgis36:
    build:
      context: .
      dockerfile: qgis.Dockerfile
    container_name: qgis36
    volumes:
      - ${PLUGIN_PATH}:/tests_directory
      - ${QGIS_PROFILE_PATH}/:/root/.local/share/QGIS/QGIS3/profiles/default
    stdin_open: true
    tty: true
    depends_on:
      - postgresdb
    hostname: ${QGIS_HOSTNAME}
    networks:
      qgis_network:
        aliases:
          - ${QGIS_HOSTNAME}
    environment:
      - DISPLAY=host.docker.internal:0
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
      - PGDATA_PATH=${PGDATA_PATH}
      - QGIS_DATA_PATH=${QGIS_DATA_PATH}
      - AUTHCFG=${AUTHCFG}

  postgresdb:
    build:
      context: .
      dockerfile: postgresql.Dockerfile
    container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${PGDATA_PATH}:/var/lib/postgresql/data
    hostname: ${POSTGRES_HOSTNAME}
    networks:
      qgis_network:
        aliases:
          - ${POSTGRES_HOSTNAME}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA_PATH=${PGDATA_PATH}
      - TEST_DATA=${TEST_DATA}

networks:
  qgis_network:
    driver: bridge
