--
-- Create extensions
--

CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "postgis";
CREATE EXTENSION postgis_topology;
CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;
